defmodule Thunderline.Repo.Migrations.CreateAgentsAndDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "agents_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :status, :text, null: false, default: "draft"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:agent_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :agent_id,
          references(:agents,
            column: :id,
            name: "agent_documents_agent_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :document_type, :text, null: false
      add :file_path, :text, null: false
      add :original_filename, :text, null: false
      add :status, :text, null: false, default: "uploaded"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:agent_documents, "agent_documents_agent_id_fkey")

    drop table(:agent_documents)

    drop constraint(:agents, "agents_user_id_fkey")

    drop table(:agents)
  end
end
