defmodule Thunderline.Repo.Migrations.FullAgentWorkflow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agents) do
      add :current_step, :bigint, null: false, default: 0
      add :training_progress, :bigint, null: false, default: 0
    end

    alter table(:agent_documents) do
      add :is_synthetic, :boolean, null: false, default: false
      add :source_document_id, :uuid
      add :synthetic_prompt, :text
      add :synthetic_reasoning, :text
      add :synthetic_response, :text
    end
  end

  def down do
    alter table(:agent_documents) do
      remove :synthetic_response
      remove :synthetic_reasoning
      remove :synthetic_prompt
      remove :source_document_id
      remove :is_synthetic
    end

    alter table(:agents) do
      remove :training_progress
      remove :current_step
    end
  end
end
